baseURL = "http://nsf-ic-education.com/"
languageCode = "en-us"
title = "NSF Integrated Circuit Research, Education, and Workforce Development Workshop"
theme = "slick"
disableKinds=["RSS"]

[params]
    # Site subtitle (not shown if commented out or set to false)
    #subtitle = "Just another site"

    # Site description
    #description = "Example site for Slick Hugo theme"

    # Favicon file (relative to baseURL - place below static or assets folder)
    favicon = "nsf.png"
    # Custom css file (relative to baseURL - place below static or assets folder)
    #css = "custom.css"

    # Define formatting of dates
    # (optional, falls back to RFC822 format if not set)
    # For reference to date and time formatting, see:
    # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
    # Make sure to set showMetaDates to true to see any dates
    dateFmt = "Mon, 02 Jan 2006 15:04:05 MST"

    # Customize the text of the 404 page here
    errorPageText = "There's nothing to see here, please move along!"

    # Header with title/subtitle can be disabled here.
    # (If you disable this, add some link on the index page inside menu.main,
    #  otherwise your visitors will get confused and lost...)
    showNavHeader = true

    # Decide if only summaries are shown on the main page or the full content
    showFullContent = true

    # If false no pagination is shown when there is nothing to paginate
    showEmptyPagination = false

    # If false the title, dates and taxonomy are not shown on single view
    showMeta = false

    # If false the dates for the posts are not shown
    showMetaDates = true

    # If false the taxonomy links for the posts are not shown
    showMetaLinks = false

    # Uses Hugo internal templates if set
    opengraph = false
    schema = false
    twitter_cards = false


[services.rss]
    # limit the length of the rss feed (default: unlimited)
    limit = 0

[author]
    name = "Matthew Guthaus"
    email = "mrg@ucsc.edu"

[menu]

    # Configure main menu entries (header)
    # Currently set to list all taxonomies and posts
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
        weight = 1

    [[menu.main]]
        identifier = "leadership"
        name = "Leadership"
        url = "/leadership"
        weight = 1

    [[menu.main]]
        identifier = "oct_meeting"
        name = "October 2021 Meeting"
        title = "October Meeting"
        url = "/oct_meeting"
        weight = 2

    [[menu.main]]
        identifier = "may_meeting"
        name = "May 2022 Meeting"
        title = "May Meeting"
        url = "/may_meeting"
        weight = 3

    [[menu.main]]
        identifier = "report"
        name = "Summary Report"
        title = "Summary Report"
        url = "/report"
        weight = 3

    # Define the entries for post metadata
    # Identifiers should match with the taxonomy entries
    [[menu.meta]]
        identifier = "oct_meeting"
        name = "October 2021 Meeting"
	url = "/oct_meeting"
        weight = 1

    # Add some footer links to your likings
    [[menu.footer]]
        name = "NSF Award #2137629"
        title = "NSF Award #2137629"
        url = "https://www.nsf.gov/awardsearch/showAward?AWD_ID=2137629"
        weight = 1
    [[menu.footer]]
      weight = 2
      name = "Baskin Engineering"
      url = "https://engineering.ucsc.edu"
    [[menu.footer]]
      weight = 3
      name = "VLSI Design and Automation"
      url = "https://vlsida.soe.ucsc.edu"
    [[menu.footer]]
      weight = 4
      name = "University of California, Santa Cruz"
      url = "https://www.ucsc.edu"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
